replicaCount: 2

image:
  repository: 851725587609.dkr.ecr.us-east-1.amazonaws.com/swiftcart-backend

  tag: latest

service:
  type: LoadBalancer
  port: 80

env:
  ENV: "base"


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70