apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MadduDeepthi/swiftcart.git
    targetRevision: main
    path: helm/fastapi
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true