name: Frontend Build

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Simulate Mobile Build
      run: |
        mkdir -p build
        echo "Dummy APK content" > build/app.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobile-apk
        path: build/app.apk